"""add is_active to moderators

Revision ID: de70dfb259c0
Revises: a9c4431e57d8
Create Date: 2026-10-03 19:14:31.246866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de70dfb259c0'
down_revision: Union[str, None] = 'a9c4431e57d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('moderators', sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('moderators', 'is_active')
    # ### end Alembic commands ###
